CustomIdentity/Controllers/JobController.cs
using CustomIdentity.Data;
using CustomIdentity.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Text.Encodings.Web;
using Microsoft.AspNetCore.Authorization;

namespace CustomIdentity.Controllers
{
	[Authorize]
	public class JobController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly UserManager<ApplicationUser> _userManager;

		public JobController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
		{
			_context = context;
			_userManager = userManager;
		}
		public async Task<IActionResult> Index()
		{
			var result = await _context.Jobs.ToListAsync();

			return View(result);
		}

		// Job/Create
		public async Task<IActionResult> Create()
		{
			var selectOptions = await SelectAssignTo();
			ViewBag.SelectOptions = selectOptions;
			return View();
		}

		public async Task<List<SelectListItem>> SelectAssignTo()
		{
			var users = await _userManager.Users.ToListAsync();
			var selectOptions = users.Select(user => new SelectListItem()
			{
				Value = $"{user.FirstName} {user.LastName}",
				Text = $"{user.FirstName} {user.LastName}"
			}).ToList();

			return selectOptions;
		}

		[HttpPost]
		public async Task<IActionResult> Create ([Bind("Id, Name, Note, JobStatus, DateStart, DeadLine, AssignTo")] Job job)
		{
			if (ModelState.IsValid)
			{
				job.Id = Guid.NewGuid();
				await _context.AddAsync(job);
				await _context.SaveChangesAsync();
			}
			else
			{
				throw new Exception("Job is invalid");
			}
			return RedirectToAction("Index");
		}

		// GET: Job/Delete/5
		[HttpGet("[controller]/delete/{jobId}")]
		public async Task<IActionResult> Delete (Guid jobId)
		{
			var job = await _context.Jobs.FirstOrDefaultAsync(j => j.Id == jobId);

			if (job == null) return NotFound();
			return View(job);
		}

		// POST: Job/Delete/5
		[HttpPost("[controller]/delete/{jobId}"), ActionName("Delete")]
		public async Task<IActionResult> DeleteConfirmed (Guid jobId)
		{
			var job = await _context.Jobs.FindAsync(jobId);
			_context.Jobs.Remove(job);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		// GET: Job/Edit/5
		//[HttpGet("[controller]/edit/{jobId}")]
		public async Task<IActionResult> Edit (Guid id)
		{
			if (id == null) return NotFound();
			var job = await _context.Jobs.FindAsync(id);
			if (job == null) return NotFound();
			var selectOptions = await SelectAssignTo();
			ViewBag.SelectOptions = selectOptions;
			return View(job);
		}

		[HttpPost]
		public async Task<IActionResult> Edit(Guid id, [Bind ("Id, Name, Note, JobStatus, DateStart, DeadLine, AssignTo")] Job job)
		{
			if (id != job.Id) return NotFound();
			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(job);
					await _context.SaveChangesAsync();
				}
				catch (Exception err)
				{

					throw new Exception(err.Message);
				}
				return RedirectToAction(nameof(Index));
			}
			return View(job);
		}

		// GET: Movies/Details/5
		public async Task<IActionResult> Details(Guid id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var job = await _context.Jobs
				.FirstOrDefaultAsync(j => j.Id == id);
			if (job == null)
			{
				return NotFound();
			}

			return View(job);
		}

	}
}

CustomIdentity/Controllers/UserRolesController.cs
using CustomIdentity.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CustomIdentity.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserRolesController : Controller
	{
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly RoleManager<IdentityRole> _roleManager;

		public UserRolesController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
		{
			_roleManager = roleManager;
			_userManager = userManager;
		}

		public async Task<IActionResult> Index()
		{
			var users =await _userManager.Users.ToListAsync();
			var userRolesViewModel = new List<UserRolesViewModel>();
			foreach (ApplicationUser user in users) 
			{
				var thisViewModel = new UserRolesViewModel();
				thisViewModel.UserId = user.Id;
				thisViewModel.Email = user.Email;
				thisViewModel.FirstName = user.FirstName;
				thisViewModel.LastName = user.LastName;
				thisViewModel.Roles = await GetUserRoles(user);
				userRolesViewModel.Add(thisViewModel);
			};

			return View(userRolesViewModel);
		}

		private async Task<List<string>> GetUserRoles(ApplicationUser user)
		{
			return new List<string>(await _userManager.GetRolesAsync(user));
		}

        public async Task<IActionResult> Manage(string userId)
        {
            ViewBag.userId = userId;
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }
            ViewBag.UserName = user.UserName;
            var model = new List<ManageUserRolesViewModel>();
            foreach (var role in _roleManager.Roles)
            {
                var userRolesViewModel = new ManageUserRolesViewModel
                {
                    RoleId = role.Id,
                    RoleName = role.Name
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesViewModel.Selected = true;
                }
                else
                {
                    userRolesViewModel.Selected = false;
                }
                model.Add(userRolesViewModel);
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Manage(List<ManageUserRolesViewModel> model, string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return View();
            }
            var roles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, roles);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing roles");
                return View(model);
            }
            result = await _userManager.AddToRolesAsync(user, model.Where(x => x.Selected).Select(y => y.RoleName));
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add selected roles to user");
                return View(model);
            }
            return RedirectToAction("Index");
        }
    }
}

CustomIdentity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - WorkFlow</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WorkFlow</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
					<partial name="_LoginPartial" />
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Trang chủ</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Job">Danh sách công việc</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="UserRoles">Quản lý phân quyền người dùng</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2022 - Workflow
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	@RenderSection("Scripts", required: false)
	<script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>