CustomIdentity/Controllers/RoleManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CustomIdentity.Controllers
{
	[Authorize(Roles = "Admin")]
	public class RoleManagerController : Controller
	{
		private readonly RoleManager<IdentityRole> _roleManager;

		public RoleManagerController(RoleManager<IdentityRole> roleManager)
		{
			_roleManager = roleManager;
		}
		public async Task<IActionResult> Index()
		{
			var roles = await _roleManager.Roles.ToListAsync();

			return View(roles);
		}


		[HttpPost]
		public async Task<IActionResult> AddRole(string roleName)
		{
			if (!String.IsNullOrEmpty(roleName))
			{
				await _roleManager.CreateAsync(new IdentityRole(roleName.Trim()));
			}
			return RedirectToAction("Index");
		}


		// GET: RoleManager/Delete/sdfst
		[HttpGet("[controller]/delete/{id}")]
		public async Task<IActionResult> Delete(string id)
		{
			var role = await _roleManager.FindByIdAsync(id);
			return View(role);
		}

		[HttpPost, ActionName("Delete")]
		public async Task<IActionResult> DeleteConfirmed(string id)
		{
			var role = await _roleManager.FindByIdAsync(id);
			if(role.Name != "Admin") await _roleManager.DeleteAsync(role);
			return RedirectToAction(nameof(Index));
		}

		// GET: RoleManager/Edit/kjkjsdsdjs
		[HttpGet("[controller]/edit/{id}")]
		public async Task<IActionResult> Edit(string id)
		{
			if (id == null) return NotFound();
			var role = await _roleManager.FindByIdAsync(id);
			if (role == null) return NotFound();
			return View(role);
		}

		[HttpPost("[controller]/edit/{id}")]
		public async Task<IActionResult> Edit (string id, [Bind("Id, Name")] IdentityRole role)
		{
			if (id != role.Id) return NotFound();
			if(ModelState.IsValid)
			{
				try
				{
					await _roleManager.UpdateAsync(role);
					return RedirectToAction(nameof(Index));

				}
				catch (Exception err)
				{
					throw new Exception(err.Message);
				}
				
			}
			return View(role);
		}

	}
}

CustomIdentity/Views/RoleManager/Delete.cshtml
@model Microsoft.AspNetCore.Identity.IdentityRole;
	

	@{
		ViewData["Title"] = "Role manager";
		Layout = "~/Views/Shared/_Layout.cshtml";
	}
	<h4>Bạn có chắc muốn xóa vai trò này?</h4>

	<table class="table table-striped">
		<thead>
			<tr>
				<th>Id</th>
				<th>Tên vai trò</th>
				<th>Hành động</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>@Model.Id</td>
				<td>@Model.Name</td>
				<td>
					<form asp-action="Delete">
						<input type="hidden" asp-for="@Model.Id" />
						<input type="submit" value="Xóa" class="btn btn-danger" />
					</form>
				</td>
			</tr>
		</tbody>
	</table>

CustomIdentity/Views/RoleManager/Edit.cshtml
@model Microsoft.AspNetCore.Identity.IdentityRole;


@{
	ViewData["Title"] = "Edit Role manager";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<h4>Chỉnh sửa tên vai trò</h4>

<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="Id" />
			<div class="form-group">
				<label asp-for="Name" class="control-label"> Tên vai trò</label>
				<input asp-for="Name" class="form-control" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
			
			<div class="form-group">
				<input type="submit" value="Lưu lại" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

CustomIdentity/Views/RoleManager/Index.cshtml
@model List<Microsoft.AspNetCore.Identity.IdentityRole>

@{
	ViewData["Title"] = "Role manager";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Quản lý phân quyền</h1>
<form method="post" asp-action="AddRole" asp-controller="RoleManager">
	<div class="input-group">
		<input name="roleName" class="form-control w-25">
		<span class="input-group-btn">
			<button class="btn btn-info">Thêm vai trò mới</button>
		</span>
	</div>
</form>
<table class="table table-striped">
	<thead>
		<tr>
			<th>Id</th>
			<th>Tên vai trò</th>
			<th>Hành động</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var role in Model)
		{
		<tr>
			<td>@role.Id</td>
			<td>@role.Name</td>
			<td>
				@if (role.Name != "Admin")
				{
					<a asp-action="Delete" asp-route-id="@role.Id" class="btn btn-danger">Xóa</a>
					@*<a asp-action="Edit" asp-route-id="@role.Id" class="btn btn-info">Sửa</a>*@
				}
			</td>
			
		</tr>
					}
	</tbody>
</table>